#ifndef CONFIG
#define CONFIG


#define INITIAL_PROMPT "Welcome to Academia Portal!\nWho are you?\n1. Admin\t2. Faculty\t3. Student\nPress any other number to exit\nEnter the number corresponding to the choice!"

// ========== COMMON TEXT =============================

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"

// ERROR
#define STUDENT_ID_DOESNT_EXIT "No student could be found for the given ID"
#define STUDENT_LOGIN_ID_DOESNT_EXIT "No student could be found for the given login ID"
#define ERRON_INPUT_FOR_NUMBER "It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"
#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"
#define FACULTY_LOGIN_ID_DOESNT_EXIT "No faculty could be found for the given login ID"


// ========== ADMIN SPECIFIC TEXT======================

// ADMIN CREDENTIALS
#define ADMIN_LOGIN_ID "admin"
#define ADMIN_PASSWORD "66WrdC8pl7zYM" // "420boo69"

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! With great power comes great responsibility!\nEnter your credentials to unlock this power!"
#define ADMIN_LOGIN_SUCCESS "Welcome superman!"

// ADMIN MENU
#define ADMIN_MENU "1. Add Student\n2. Add Faculty\n3. Update Student Details\n4. Update Faculty Details\nPress any other key to logout"

// ADD STUDENT
#define ADMIN_ADD_STUDENT_NAME "What is the student's name?"
#define ADMIN_ADD_STUDENT_EMAIL "What is the students's Email ID?"
#define ADMIN_ADD_STUDENT_AUTOGEN_LOGIN "The autogenerated login ID for the student is : "
#define AUTOGEN_PASSWORD "student" // append to end of next string macro
#define ADMIN_ADD_STUDENT_AUTOGEN_PASSWORD "The autogenerated password for the student is : "

// MODIFY STUDENT INFO
#define ADMIN_MOD_STUDENT_ID "Enter the ID of the student who's information you want to edit"
#define ADMIN_MOD_STUDENT_MENU "Which information would you like to modify?\n1. Name 2. Email 3. Password 4. StudentStatus \nPress any other key to cancel"
#define ADMIN_MOD_STUDENT_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_STUDENT_NEW_EMAIL "What's the updated value for email?"
#define ADMIN_MOD_STUDENT_NEW_PASSWORD "What's the updated value for password?"
#define ADMIN_MOD_STUDENT_NEW_STATUS "What's the updated value for student status \n 1. Activate 2. Deactivate"


// ADD FACULTY
#define ADMIN_ADD_FACULTY_NAME "What is the Faculty's name?"
#define ADMIN_ADD_FACULTY_EMAIL "What is the Faculty's Email ID?"
#define ADMIN_ADD_FACULTY_AUTOGEN_LOGIN "The autogenerated login ID for the Faculty is : "
#define AUTOGEN_FACULTY_PASSWORD "faculty" // append to end of next string macro
#define ADMIN_ADD_FACULTY_AUTOGEN_PASSWORD "The autogenerated password for the Faculty is : "

// MODIFY FACULTY INFO
#define ADMIN_MOD_FACULTY_ID "Enter the ID of the Faculty who's information you want to edit"
#define ADMIN_MOD_FACULTY_MENU "Which information would you like to modify?\n1. Name 2. Email 3. Password\nPress any other key to cancel"
#define ADMIN_MOD_FACULTY_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_FACULTY_NEW_EMAIL "What's the updated value for email?"
#define ADMIN_MOD_FACULTY_NEW_PASSWORD "What's the updated value for password?"


#define ADMIN_MOD_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

#define ADMIN_LOGOUT "Logging you out now superman! Good bye!$"

// ====================================================

// ========== FACULTY SPECIFIC TEXT===================

// LOGIN WELCOME
#define FACULTY_LOGIN_WELCOME "Welcome dear faculty! Enter your credentials to gain access to your account!"
#define FACULTY_LOGIN_SUCCESS "Welcome beloved faculty!"

#define FACULTY_LOGOUT "Logging you out now dear faculty! Good bye!$"

// FACULTY MENU
#define FACULTY_MENU "1. Add Course\n2. Remove Offered Course\n3. View Enrollments in Course\n4. Change Password\nPress any other key to logout"

// ADD COURSE
#define FACULTY_ADD_COURSE_NAME "What is the course's name?"
#define FACULTY_REMOVE_COURSE "What is the course ID to be removed?"
#define FACULTY_VIEW_COURSE_ENROLLENT "Enrollments in the course are"
#define FACULTY_ADD_COURSE_SUCCESS "Course has been created successfully!"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ====================================================


#define COURSE_FILE "DB/course.txt"
#define STUDENT_FILE "DB/student.txt"
#define FACULTY_FILE "DB/faculty.txt"

#define COURSE_MAX_SEATS 10

#endif